### ISSUE TITLE
TypeError: deepCopy is not a function

### ISSUE THREAD

**Issue by selfagency** [kgryte/error-to-json#1]
just tried to use this in a project and got this error:

```
TypeError: deepCopy is not a function
    at copy (/my_project/node_modules/utils-copy-error/lib/copy.js:51:17)
    at deepCopy (/my_project/node_modules/utils-copy/lib/deepcopy.js:105:10)
    at createCopy (/my_project/node_modules/utils-copy/lib/index.js:34:9)
    at toJSON (/my_project/node_modules/utils-error-to-json/lib/index.js:52:20)
    at handler (/my_project/modules/errors.js:29:15)
    at Server.server.on (/my_project/modules/errors.js:44:54)
    at emitMany (events.js:147:13)
    at Server.emit (events.js:224:7)
    at emitError (/my_project/node_modules/restify/lib/server.js:1308:22)
    at Array.<anonymous> (/my_project/node_modules/vasync/lib/vasync.js:246:12)
    at pipeline (/my_project/node_modules/vasync/lib/vasync.js:219:10)
    at Object.forEachPipeline (/my_project/node_modules/vasync/lib/vasync.js:250:13)
    at Server._emitErrorEvents (/my_project/node_modules/restify/lib/server.js:1304:19)
    at Server._routeErrorResponse (/my_project/node_modules/restify/lib/server.js:1239:10)
    at Server._onHandlerError (/my_project/node_modules/restify/lib/server.js:1074:10)
    at Server._afterRoute (/my_project/node_modules/restify/lib/server.js:947:14)
    at Immediate.afterRouter [as _onImmediate] (/my_project/node_modules/restify/lib/server.js:923:18)
    at runCallback (timers.js:795:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by SMorettini** [comment]
I have the same error.

**Comment by corbmanj** [comment]
Has anyone found a resolution to this issue? Does deepcopy need to be installed as a peer?

**Comment by kgryte** [comment]
@corbmanj I believe the issue concerns circular dependencies, but have not thoroughly investigated.

For an alternative, core development has moved to [`stdlib`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/error/to-json), which provides similar functionality.

**Comment by selfagency** [comment]
closing this because it's 4 years old, this project is defunct, and i want to clean up my issues tab
